# Generated by Django 4.2.7 on 2023-12-08 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "law",
                    models.CharField(
                        choices=[("44-FZ", "44-ФЗ"), ("223-FZ", "223-ФЗ")],
                        max_length=255,
                    ),
                ),
                (
                    "procurement_method",
                    models.CharField(
                        choices=[("single_supplier", "Единственный поставщик")],
                        max_length=255,
                    ),
                ),
                (
                    "conclusion_basis",
                    models.CharField(
                        choices=[
                            (
                                "c4p1",
                                "п. 4 ч. 1 ст. 93 Закупка объемом до 600 тысяч рублей",
                            ),
                            (
                                "c5p1",
                                "п. 5 ч. 1 ст. 93 Закупка объёмом до 600 тысяч рублей",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("number", models.TextField()),
                ("validity_period_start", models.DateField()),
                ("validity_period_end", models.DateField()),
                ("contract_subject", models.TextField()),
                ("conclusion_place", models.CharField(max_length=255)),
                (
                    "procurement_id",
                    models.CharField(
                        max_length=36,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "Введите число."
                            )
                        ],
                    ),
                ),
                (
                    "financing_source",
                    models.CharField(
                        choices=[
                            ("budget", "Бюджетные средства"),
                            ("non_budget", "Небюджетные средства"),
                            ("oms", "Средства ОМС"),
                        ],
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("advance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("signer", models.TextField()),
                ("general_info", models.TextField()),
                ("bank_details", models.TextField()),
                ("contact_details_phone", models.CharField(max_length=15)),
                ("contact_details_email", models.EmailField(max_length=254)),
                ("delivery_info", models.TextField()),
                (
                    "customer_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performer_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performer_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("delivery_term", models.CharField(max_length=200)),
                ("product_name", models.CharField(max_length=200)),
                (
                    "price_with_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity", models.IntegerField()),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "main_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_configs",
                        to="decision.maincontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("okpd2", models.CharField(max_length=255)),
                (
                    "price_with_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity", models.IntegerField()),
                ("vat", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "main_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="decision.maincontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMainContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "law",
                    models.CharField(
                        choices=[("44-FZ", "44-ФЗ"), ("223-FZ", "223-ФЗ")],
                        max_length=255,
                    ),
                ),
                (
                    "procurement_method",
                    models.CharField(
                        choices=[("single_supplier", "Единственный поставщик")],
                        max_length=255,
                    ),
                ),
                (
                    "conclusion_basis",
                    models.CharField(
                        choices=[
                            (
                                "c4p1",
                                "п. 4 ч. 1 ст. 93 Закупка объемом до 600 тысяч рублей",
                            ),
                            (
                                "c5p1",
                                "п. 5 ч. 1 ст. 93 Закупка объёмом до 600 тысяч рублей",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("number", models.TextField()),
                ("validity_period_start", models.DateField()),
                ("validity_period_end", models.DateField()),
                ("contract_subject", models.TextField()),
                ("conclusion_place", models.CharField(max_length=255)),
                (
                    "procurement_id",
                    models.CharField(
                        max_length=36,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "Введите число."
                            )
                        ],
                    ),
                ),
                (
                    "financing_source",
                    models.CharField(
                        choices=[
                            ("budget", "Бюджетные средства"),
                            ("non_budget", "Небюджетные средства"),
                            ("oms", "Средства ОМС"),
                        ],
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("advance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("signer", models.TextField()),
                ("general_info", models.TextField()),
                ("bank_details", models.TextField()),
                ("contact_details_phone", models.CharField(max_length=15)),
                ("contact_details_email", models.EmailField(max_length=254)),
                ("delivery_info", models.TextField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "customer_details",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performer_details",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical main contract",
                "verbose_name_plural": "historical main contracts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
