# Generated by Django 4.2.7 on 2023-12-10 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decision", "0002_historicalmaincontract_is_being_edited_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="advance",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="bank_details",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="conclusion_basis",
            field=models.CharField(
                choices=[
                    ("c4p1", "п. 4 ч. 1 ст. 93 Закупка объемом до 600 тысяч рублей"),
                    ("c5p1", "п. 5 ч. 1 ст. 93 Закупка объёмом до 600 тысяч рублей"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="conclusion_place",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="contact_details_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="contact_details_phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="contract_subject",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="delivery_info",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="financing_source",
            field=models.CharField(
                choices=[
                    ("budget", "Бюджетные средства"),
                    ("non_budget", "Небюджетные средства"),
                    ("oms", "Средства ОМС"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="general_info",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="law",
            field=models.CharField(
                choices=[("44-FZ", "44-ФЗ"), ("223-FZ", "223-ФЗ")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="number",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="procurement_id",
            field=models.CharField(
                max_length=36,
                null=True,
                validators=[
                    django.core.validators.RegexValidator("^\\d+$", "Введите число.")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="procurement_method",
            field=models.CharField(
                choices=[("single_supplier", "Единственный поставщик")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="signer",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="validity_period_end",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaincontract",
            name="validity_period_start",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="advance",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="bank_details",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="conclusion_basis",
            field=models.CharField(
                choices=[
                    ("c4p1", "п. 4 ч. 1 ст. 93 Закупка объемом до 600 тысяч рублей"),
                    ("c5p1", "п. 5 ч. 1 ст. 93 Закупка объёмом до 600 тысяч рублей"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="conclusion_place",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="contact_details_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="contact_details_phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="contract_subject",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="delivery_info",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="financing_source",
            field=models.CharField(
                choices=[
                    ("budget", "Бюджетные средства"),
                    ("non_budget", "Небюджетные средства"),
                    ("oms", "Средства ОМС"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="general_info",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="law",
            field=models.CharField(
                choices=[("44-FZ", "44-ФЗ"), ("223-FZ", "223-ФЗ")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="number",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="procurement_id",
            field=models.CharField(
                max_length=36,
                null=True,
                validators=[
                    django.core.validators.RegexValidator("^\\d+$", "Введите число.")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="procurement_method",
            field=models.CharField(
                choices=[("single_supplier", "Единственный поставщик")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="signer",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="validity_period_end",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="maincontract",
            name="validity_period_start",
            field=models.DateField(null=True),
        ),
    ]
