# Generated by Django 4.2.7 on 2023-12-10 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("decision", "0004_alter_historicalmaincontract_advance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmaincontract",
            name="delivery_info",
        ),
        migrations.RemoveField(
            model_name="historicalmaincontract",
            name="validity_period_end",
        ),
        migrations.RemoveField(
            model_name="historicalmaincontract",
            name="validity_period_start",
        ),
        migrations.RemoveField(
            model_name="maincontract",
            name="delivery_info",
        ),
        migrations.RemoveField(
            model_name="maincontract",
            name="validity_period_end",
        ),
        migrations.RemoveField(
            model_name="maincontract",
            name="validity_period_start",
        ),
    ]
