# Generated by Django 4.2.7 on 2023-12-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("decision", "0001_initial"),
        ("chat", "0004_chat_legacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="legacy",
        ),
        migrations.AddField(
            model_name="chat",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="main_form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="decision.maincontract",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="status",
            field=models.CharField(default="active", max_length=255),
        ),
    ]
