# Generated by Django 4.2.7 on 2023-12-09 23:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_rename_main_form_chat_main_contract"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="is_read",
            new_name="is_system",
        ),
    ]
