# Generated by Django 4.2.7 on 2023-12-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Заголовой для вашей услуги", max_length=60
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Напишите о своей услуге.", max_length=1000
                    ),
                ),
                ("main_form", models.JSONField()),
            ],
        ),
    ]
